DATA = {
    "existence": ["data/visual7w/images/",
                  'data/existence.json'],
    "plurals": ["data/plurals/test_images/",
                'data/plurals.json'],
    "counting_hard": ["data/visual7w/images/",
                      'data/counting_hard.json'],
    "counting_small": ['data/visual7w/images/',
                       'data/counting-small-quant.json'],
    "counting_adversarial": ["data/visual7w/images/",
                             'data/counting_adversarial.json'],
    "relations": ["data/relations/test_images/",
                  'data/relation.json'],
    "action replace": ['data/actions/images_512/',
                       'data/action-replacement.json'],
    "actant swap": ['data/actions/images_512/',
                    'data/actions/actant-swap.json'],
    "coref": ["data/coref/release_too_many_is_this_in_color/images/",
              'data/coreference-standard.json'],
    "coref_hard": ["data/coref/release_v18/test_images/",
                   'data/coreference-hard.json'],
    "foil_it": ["/scratch/COCO/val2014/",
                "data/foil-it.json"],
}
